# Site settings
course_name: Reinforcement Learning
course_description: ""
course_semester: "Spring 2025"

baseurl: "/Rl_course_SM.github.io" # the subpath of your site, e.g. /blog/
url: "http:///kumarr99.github.io/" # the base hostname & protocol for your site

schoolname: "Plaksha Uniiversity"
schoolurl: "https://plaksha.edu.in"
twitter_username: username 

address: |
    Plaksha University
    Mohali
    Punjab

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
